AMBARI-8316. Bootstaraping and starting agents as non-root (aonishuk)

diff --git a/ambari-agent/conf/unix/ambari-agent b/ambari-agent/conf/unix/ambari-agent
--- a/ambari-agent/conf/unix/ambari-agent
+++ b/ambari-agent/conf/unix/ambari-agent
@@ -48,6 +48,12 @@ AMBARI_AGENT_PY_SCRIPT=/usr/lib/python2.6/site-packages/ambari_agent/AmbariAgent
 OK=1
 NOTOK=0
 
+current_user=`awk -v val=$EUID -F ":" '$3==val{print $1}' /etc/passwd`
+# setup necessary ownership
+sudo chown -R $current_user "/var/lib/ambari-agent/ambari-env.sh"
+sudo chown -R $current_user "/var/run/ambari-agent"
+sudo chown -R $current_user "/var/log/ambari-agent"
+sudo chown -R $current_user "/var/lib/ambari-agent/data"
 
 if [ -a /usr/bin/python2.7 ] && [ -z "$PYTHON" ]; then
   PYTHON=/usr/bin/python2.7
@@ -106,8 +112,9 @@ check_python_version ()
 
 retcode=0
 
-if [ "$(id -u)" != "0" ]; then
- echo "You can't perform this operation as non-root user. Please, re-login as root user"
+sudo -v
+if [ "$?" != "0" ]; then
+ echo "You can't perform this operation as non-sudoer user. Please, re-login as one"
  exit 0
 fi
 
